( This file tests Forth syntax highlighting.
  The goal is that it will cover all functionality.
  Please update this file as you make changes. )

\ --- Comments

\ comments are highlighted like this...
( ...or this... )
( ...multi-line comments
  are fine too! )
.( Somehow, this also counts as a comment. )
0 [IF] comment [ENDIF]
0 [IF] comment [THEN]
FALSE [IF] comment [ENDIF]
FALSE [IF] comment [THEN]

\ --- Strings

\ Verify that strings have their own color.
S" s-quote"
C" c-quote"
S\" s-backslash-quote"
." dot-quote"
FOO" custom string matching word"

\ Verify that escaped characters have their own color.
S\" \a\b\e\f\l\m\n\q\r\t\v\z\"\xff\x00\\"

\ Upper-case characters cannot be escaped.
S\" \A\B\E\F\L\M\N\Q\R\T\V\Z\Xff\X00"

\ --- Spell Checking

( activate spell checking by ":set spell"
then, verify that the below "mispelt"
words are highlighted. )
S" mispelt"
C" mispelt"
( mispelt )
\ mispelt
S\" mispelt"

\ --- To Do

\ TODO FIXME XXX

\ --- Ignore Case

dup DUP Dup

\ --- iskeyword

dup-drop \ dup and drop should not be highlighted

\ --- Keywords

\ basic mathematical and logical operators
+ - * / MOD /MOD NEGATE ABS MIN MAX
AND OR XOR NOT LSHIFT RSHIFT INVERT 2* 2/ 1+
1- 2+ 2- 8* UNDER+
*/ */MOD M* UM* M*/ UM/MOD FM/MOD SM/REM
F+ F- F* F/ FNEGATE FABS FMAX FMIN FLOOR FROUND
F** FSQRT FEXP FEXPM1 FLN FLNP1 FLOG FALOG FSIN
FCOS FSINCOS FTAN FASIN FACOS FATAN FATAN2 FSINH
FCOSH FTANH FASINH FACOSH FATANH F2* F2/ 1/F
F~REL F~ABS F~
0< 0<= 0<> 0= 0> 0>= < <= <> = > >= U< U<=
U> U>= D0<= D0<> D0> D0>= D<= D<>
D> D>= DU<= DU> DU>= WITHIN ?NEGATE
?DNEGATE

\ various words that take an input and do something with it
. U. .R U.R

\ stack manipulations
DROP NIP DUP OVER TUCK SWAP ROT -ROT ?DUP PICK ROLL
2DROP 2NIP 2DUP 2OVER 2TUCK 2SWAP 2ROT 2-ROT
3DUP 4DUP 5DUP 3DROP 4DROP 5DROP 8DROP 4SWAP 4ROT
4-ROT 4TUCK 8SWAP 8DUP
>R R> R@ RDROP 2>R 2R> 2R@ 2RDROP
4>R 4R> 4R@ 4RDROP
FDROP FNIP FDUP FOVER FTUCK FSWAP FROT

\ stack pointer manipulations
SP@ SP! FP@ FP! RP@ RP! LP@ LP! DEPTH

\ address operations
@ ! +! C@ C! 2@ 2! F@ F! SF@ SF! DF@ DF!
CHARS CHAR+ CELLS CELL+ CELL ALIGN ALIGNED FLOATS
FLOAT+ FLOAT FALIGN FALIGNED SFLOATS SFLOAT+
SFALIGN SFALIGNED DFLOATS DFLOAT+ DFALIGN DFALIGNED
MAXALIGN MAXALIGNED CFALIGN CFALIGNED
ADDRESS-UNIT-BITS ALLOT
MOVE ERASE FILL BLANK UNUSED

\ conditionals
IF ELSE ENDIF THEN CASE OF ENDOF ENDCASE ?DUP-IF
?DUP-0=-IF CATCH THROW WITHIN
BEGIN WHILE REPEAT UNTIL AGAIN
?DO LOOP I J K +DO U+DO -DO U-DO DO +LOOP -LOOP
UNLOOP LEAVE ?LEAVE EXIT DONE FOR NEXT RECURSE

\ new words
; ;M ;CLASS ;OBJECT
CONSTANT 2CONSTANT FCONSTANT VARIABLE 2VARIABLE
FVARIABLE CREATE USER VALUE TO DEFER IS <BUILDS DOES> IMMEDIATE
COMPILE-ONLY COMPILE RESTRICT INTERPRET POSTPONE EXECUTE
LITERAL CREATE-INTERPRET/COMPILE INTERPRETATION>
<INTERPRETATION COMPILATION> <COMPILATION ] LASTXT
COMP' POSTPONE, FIND-NAME NAME>INT NAME?INT NAME>COMP
STATE C; CVARIABLE BUFFER: MARKER
, 2, F, C, COMPILE,

\ debugging
PRINTDEBUGDATA PRINTDEBUGLINE

\ Assembler
FLUSH-ICACHE C,

\ basic character operations
(.) EXPECT FIND WORD TYPE EMIT KEY
TIB CR BL COUNT SPACE SPACES

\ char-number conversion
<<# <# # #> #>> #S (NUMBER) (NUMBER?) CONVERT D>F
DIGIT DPL F>D HLD HOLD NUMBER S>D SIGN >NUMBER
F>S S>F HOLDS

\ interpreter, wordbook, compiler
(LOCAL) COLD ABORT >BODY >NEXT >LINK CFA >VIEW HERE
PAD VIEW VIEW> N>LINK NAME> LINK> L>NAME
BODY> ASSERT( ASSERT0( ASSERT1( ASSERT2( ASSERT3( )
>IN ACCEPT ENVIRONMENT? EVALUATE QUIT SOURCE ACTION-OF
DEFER! DEFER@ PARSE PARSE-NAME REFILL RESTORE-INPUT
SAVE-INPUT SOURCE-ID

\ vocabularies
ROOT SEAL VOCS CONTEXT #VOCS VOCABULARY

\ File keywords
R/O R/W W/O BIN
OPEN-FILE CREATE-FILE CLOSE-FILE DELETE-FILE
RENAME-FILE READ-FILE READ-LINE KEY-FILE
KEY?-FILE WRITE-FILE WRITE-LINE EMIT-FILE
FLUSH-FILE FILE-STATUS FILE-POSITION
REPOSITION-FILE FILE-SIZE RESIZE-FILE
SLURP-FILE SLURP-FID STDIN STDOUT STDERR
INCLUDE-FILE INCLUDED REQUIRED
OPEN-BLOCKS USE LOAD --> BLOCK-OFFSET
GET-BLOCK-FID BLOCK-POSITION LIST SCR BLOCK
BUFER EMPTY-BUFFERS EMPTY-BUFFER UPDATE UPDATED?
SAVE-BUFFERS SAVE-BUFFER FLUSH THRU +LOAD +THRU
BLOCK-INCLUDED BLK

\ The optional Blocks word set
BLK BLOCK BUFFER FLUSH LOAD SAVE-BUFFERS UPDATE
EMPTY-BUFFERS LIST REFILL SCR THRU

\ The optional Double-Number word set
DABS D.R D= DMAX DMIN D- DNEGATE D+ D2/ D2* DU< D0= D0< D. D<
D>S M+ M*/ 2CONSTANT 2LITERAL 2ROT 2VALUE 2VARIABLE

\ The optional Exception word set
ABORT ABORT" message"
CATCH THROW

\ The optional Facility word set
AT-XY BEGIN-STRUCTURE CFIELD: EKEY EKEY? EKEY>CHAR EKEY>FKEY
EMIT? END-STRUCTURE FIELD: K-ALT-MASK K-CTRL-MASK K-DELETE
K-DOWN K-END K-F3 K-F4 K-F5 K-F6 K-F7 K-F8 K-F9 K-F1 K-F11 K-F12
K-F10 K-F2 K-HOME K-INSERT K-LEFT K-NEXT K-PRIOR K-RIGHT
K-SHIFT-MASK K-UP KEY? MS PAGE +FIELD TIME&DATE

\ The optional File-Access word set
BIN CLOSE-FILE CREATE-FILE DELETE-FILE FILE-POSITION FILE-SIZE
FILE-STATUS FLUSH-FILE INCLUDE-FILE INCLUDED OPEN-FILE R/O R/W
READ-FILE READ-LINE RENAME-FILE REPOSITION-FILE REQUIRED
RESIZE-FILE W/O

\ The optional Floating-Point word set
DFALIGN DFALIGNED DFFIELD: DF@ DFLOAT+ DFLOATS DF! D>F FABS
FACOS FACOSH FALIGN FALIGNED FALOG FASIN FASINH FATAN FATANH
FATAN2 FCONSTANT FCOS FCOSH FDEPTH FDROP FDUP F/ FEXP FEXPM1 FE.
FFIELD: F@ FLITERAL FLN FLNP1 FLOAT+ FLOATS FLOG FLOOR FMAX FMIN
F- FNEGATE FOVER F+ FROT FROUND FSIN FSINCOS FSINH FSQRT FSWAP
FS. F! FTAN FTANH FTRUNC F* F** FVALUE FVARIABLE F0= F0< F. F<
F~ F>D F>S PRECISION REPRESENT SET-PRECISION SFALIGN SFALIGNED
SFFIELD: SF@ SFLOAT+ SFLOATS SF! S>F >FLOAT

\ The optional Memory-Allocation word set
ALLOCATE FREE RESIZE

\ The optional Programming-Tools word set
[DEFINED] [ELSE] [IF] [THEN] [UNDEFINED] ASSEMBLER CODE END-CODE
;CODE AHEAD CS-PICK CS-ROLL .S ? DUMP SEE WORDS
NAME>COMPILE NAME>INTERPRET NAME>STRING SYNONYM
TRAVERSE-WORDLIST BYE FORGET NR> N>R

\ The optional Search-Order word set
ALSO DEFINITIONS FIND FORTH-WORDLIST FORTH GET-CURRENT GET-ORDER
ONLY ORDER PREVIOUS SEARCH-WORDLIST SET-CURRENT SET-ORDER
WORDLIST

\ The optional String word set
-TRAILING /STRING BLANK CMOVE CMOVE> COMPARE
SEARCH SLITERAL REPLACES SUBSTITUTE UNESCAPE

\ The optional Extended-Character word set
[CHAR] ( 
CHAR ( 
EKEY>XCHAR -TRAILING-GARBAGE PARSE +X/STRING X-SIZE X-WIDTH
XC-SIZE XC-WIDTH XC, XC@+ XCHAR- XCHAR+ XC!+ XC!+? XEMIT XHOLD
XKEY XKEY? X\STRING-

\ booleans
TRUE FALSE

\ numbers
DECIMAL HEX BASE

\ --- Character Matching

[CHAR] ( this-is-not-a-comment
CHAR ( this-is-not-a-comment

\ --- Abort

ABORT ABORT" message"

ABORT" message
not-continued-message

\ --- Numbers

123 #123 -123 #-123
$123 $cafe $-123 $-cafe
%1010 %-1010

123. #123. -123. #-123.
$123. $cafe. $-123. $-cafe.
%1010. %-1010.

1E 1.E 1.E0 +1.23E-1 -1.23E+1

\ --- Includes

INCLUDE filename
REQUIRE filename

\ vim: set tw=64:
